varieble = int(input("age"))
def age (age):
    if age ==   1:
        print("you will be 18 in 17 years")
    elif age == 2:
        print("you will be 18 in 16 years")
    elif age == 3:
          print("you will be 18 in 15 years")
    elif age == 4:
          print("you will be 18 in 14 years")
    elif age == 5:
          print("you will be 18 in 13 years")
    elif age == 6:
          print("you will be 18 in 12 years")
    elif age == 7:
          print("you will be 18 in 11 years")
    elif age == 8:
          print("you will be 18 in 10 years")
    elif age == 9:
          print("you will be 18 in 9 years")
    elif age == 10:
          print("you will be 18 in 8 years")
    elif age == 11:
          print("you will be 18 in 7 years")
    elif age == 12:
          print("you will be 18 in 6 years")
    elif age == 13:
          print("you will be 18 in 5 years")
    elif age == 14:
          print("you will be 18 in 4 years")
    elif age == 15:
          print("you will be 18 in 3 years")
    elif age == 16:
        print("you will be 18 in 2 years")
    elif age == 17:
          print("you will be 18 in 1 years")
    elif age == 18:
          print("you are 18")
age(varieble)
        